ED-148/feat: Add geo info to int. legal entity
rbkmoney/damsel pull request #669
Opened 2021-05-12 13:18 UTC by arikai

Заметка по именованию: https://en.wikipedia.org/wiki/Trade_bloc

2021-05-12 13:42 UTC, kpy3 requested changes

2021-05-12 13:42 UTC, kpy3 commented on proto/domain.thrift
> +    6: optional string country
```suggestion
    6: optional Residence country
```

2021-05-12 13:42 UTC, kpy3 commented on proto/domain.thrift
> +    7: optional string trade_bloc
Кмк здесь должен быть настраиваемый справочник, a-la `PaymentSystem` (только без Legacy-части)

2021-05-12 13:50 UTC, arikai commented on proto/domain.thrift
> +    7: optional string trade_bloc
Вроде такого?

2021-05-13 10:58 UTC, kpy3 commented on proto/domain.thrift
> +    7: optional string trade_bloc
Да, ещё нужно Ref сюда добавить: https://github.com/rbkmoney/damsel/blob/master/proto/domain.thrift#L3090 и сюда https://github.com/rbkmoney/damsel/blob/master/proto/domain.thrift#L3139 `TradeBlocObject` (всместе с созданием этой структуры выше)

Кстати, почему `Bloc`? 🤔

2021-05-13 12:26 UTC, arikai commented on proto/domain.thrift
> +    7: optional string trade_bloc
>Да, ещё нужно Ref сюда добавить

Добавил 👍 

Кстати, поменял ID на ObjectID (т.е. i32). Это верно?

>Кстати, почему Bloc? 🤔

См. тело PR :)
>Заметка по именованию: https://en.wikipedia.org/wiki/Trade_bloc

2021-05-13 12:55 UTC, kpy3 commented on proto/domain.thrift
> +    7: optional string trade_bloc
> Кстати, поменял ID на ObjectID (т.е. i32). Это верно?
> 
Лучше строкой оставить

2021-05-13 13:00 UTC, kpy3 commented on proto/domain.thrift
> +    7: optional string trade_bloc
> > Заметка по именованию: https://en.wikipedia.org/wiki/Trade_bloc

OMG... 🤔 
Если оно такое... развесистое, может тогда стоит учесть это в протоколе? Не всю структуру кодировать, а пока только Union c вариантом экономической зоны, которая будет ссылаться на справочное значение. Тогда, если понадобиться, мы сможем легко расширить тут потенциальные значения. @keynslug что скажешь?

2021-05-13 13:10 UTC, arikai commented on proto/domain.thrift
> +    7: optional string trade_bloc
> Если оно такое... развесистое, может тогда стоит учесть это в протоколе?

Как я понял, это наиболее общий термин, который, думаю, как раз и имеет смысл здесь использовать. Отсюда и выбор.

---

Касательно остального нужны детали того, что предлагаешь. Bottom line – можно действительно захардкодить в юнион `EEA` и `Unknown` (Other). Вопрос, что в дальнейшем с миграцией 🤔

2021-05-13 14:00 UTC, kpy3 commented on proto/domain.thrift
> +    7: optional string trade_bloc
Предлагаю как-то так (исходя из https://en.wikipedia.org/wiki/List_of_multilateral_free-trade_agreements)

```
struct InternationalLegalEntity {
    ...
     /* Экономическая зона/блок Мерчанта */
     7: optional set<TradeBloc> trade_blocs
 }

 union TradeBloc {
    1: MultilateralFreeTradeAgreement multilateral_freetrade_agreement
 }

 union MultilateralFreeTradeAgreement {
    1: OperatingAgreementRef operating_agreement
 }

struct OperatingAgreementRef {
    1: required string id
}

struct OperatingAgreement {
    1: required string name
    2: optional string description    
}

```

В дальнейшем если надо будет, можно будет добавить ещё вариантов блоков и справочников к ним

2021-05-13 14:07 UTC, tolkonepiu requested changes

2021-05-13 14:07 UTC, tolkonepiu commented on proto/domain.thrift
> +    6: optional Residence residence
Не вижу итоговой связи страны с экономической зоной

2021-05-13 14:07 UTC, tolkonepiu commented on proto/domain.thrift
> +struct TradeBloc {
По этому справочнику нельзя будет узнать, какие страны находятся в этой экономической зоне

2021-05-13 15:05 UTC, arikai commented on proto/domain.thrift
> +    7: optional string trade_bloc
Но ведь принадлежность к блокам исходит из страны, в которой находится мерч 🤔 

Иными словами, принадлежность к блоку определяется:
1. Страной, в которой находится мерчант
2. Видом деятельности мерчанта (как я понимаю из [приложенной статьи из вики](https://en.wikipedia.org/wiki/List_of_multilateral_free-trade_agreements), может распространяться на определённые виды деятельности/услуг/товаров)

Второй пункт мне кажется достаточно редким и неважным явлением в рамках системы, чтобы сейчас обращать на него внимание.

---

Подытоживая, получается следующая схема:
1. Контрактор является резидентом определённой Страны
2. Каждая Страна состоит в 0 и более Торговых Блоках
3. Транзитивно, Контрактор ведёт деятельность в 0 и более Торговых блоках
4. Торговый Блок – общее именование союза между Странами
5. Помимо [соглашений между Торговыми Блоками](https://en.wikipedia.org/wiki/List_of_multilateral_free-trade_agreements), [соглашения могут и между гетерогенными сущностями (страна/блок/набор стран)](https://en.wikipedia.org/wiki/List_of_bilateral_free-trade_agreements)

Данная схема является более полной и корректной, но очевидно сложной для понимания и работы с ней: действительно ли нужно подобное в рамках системы? 🤔 (особенно с учётом того, что использование исключительно внутреннее: тогд) 

---

### Вопросы
0. Действительно ли нужен задел на будущее в виде такой развесистой реализации? (нужен фидбек от стейкхолдеров? 🤔)
`-- дальнейшие вопросы не имеют смысла при примитивной реализации --`
1. Исходя из п.3: нужно ли явно указывать у Контрактора экономическую зону?
2. Как будет осуществляться работа системы при добавлении/изменении/удалении блоков?
3. А при изменении состава блоков (входящих стран)?

2021-05-13 15:11 UTC, arikai commented on proto/domain.thrift
> +struct TradeBloc {
Действительно, данное требование упустил.

Однако непонятно, что будет при дальнейшем добавлении блоков с пересекающимися странами, т.к. [требование гласит](https://rbkmoney.atlassian.net/browse/BUSINESS-80):
> Если страна включена в данный справочник, то ставится признак «EEA».

Ну и пачка других вопросов, изложенных здесь: https://github.com/rbkmoney/damsel/pull/669#discussion_r631881247

2021-05-13 15:34 UTC, kpy3 commented on proto/domain.thrift
> +    7: optional string trade_bloc
Я исхожу из мудрости "аппетит приходит во время еды". То есть сейчас требуется маркер для отчётов, но в будущем может понадобиться что-то более сложное и/или другое. Вижу тут два пути:
1. Сделать структуру для зон сразу и потом её расширять
2. Сделать конкретный простой справочник для конкретной вещи и отложить вопрос до "потом".

Предлагаемый вариант позволяет задавать сразу несколько блоков, справочники можно заводить постепенно, типы блоков добавлять постепенно, при изменении составов блоков они либо не поменяют аббревиатуру, либо появятся новые значения в справочниках.

2021-05-13 15:41 UTC, kpy3 commented on proto/domain.thrift
> +struct TradeBloc {
А нужно ли это знание?

2021-05-13 15:43 UTC, arikai commented on proto/domain.thrift
> +    7: optional string trade_bloc
В таком случае предлагаю что-то вроде:
```thrift
struct InternationalLegalEntity {
  ...
  /* Страна Мерчанта */
  6: optional Residence residence
  /* Проассоциированные (применимые) Экономическая зона/блок Мерчанта */
  7: optional set<TradeBlocRef> trade_blocs
}

typedef base.ID TradeBlocID

struct TradeBlocRef {
  1: required TradeBlocID id
}

struct TradeBloc {
  1: required string name
  2: optional string description
  3: required set<Residence> members
}
```

Таким образом:
1. Пока не трогаем соглашения (agreement) – чувствую, что потребуется более сложная модель. Сейчас, как я понимаю, важны именно сами зоны, сиреч блоки.
2. С мерчантом будут проассоциированы 0 или более блоков, но выбраны они будут вручную из тех, что применимы (для выбранной страны)

2021-05-13 15:43 UTC, kpy3 commented on proto/domain.thrift
> +struct TradeBloc {
Если идти от страны к одному из вариантов блока, то это кажется совсем иначе делать надо 🤔

2021-05-13 15:49 UTC, kpy3 commented on proto/domain.thrift
> +struct TradeBloc {
Что-то типа
```
struct InternationalLegalEntity {
    ...
    optional CountryRef country
 }


struct CountryRef {
    1: required Residence id
}

struct Country {
    1: required string name
    2: set<TradeBlocRef> trade_blocs    
}


struct TradeBlocRef {
    1: required string id
}

struct TradeBloc {
    1: required string name
    2: optional string description    
}
```

2021-05-13 17:31 UTC, keynslug commented on proto/domain.thrift
> +struct TradeBloc {
> Что-то типа

Бегло пролистав дискуссию, поддержу этот вариант. Правда эпик не рассчитывает на то, что у одной страны может быть скажем 7 экономических зон, но это кажется вопрос к аналитике.

2021-05-14 05:30 UTC, arikai commented on proto/domain.thrift
> +struct TradeBloc {
> Что-то типа
Тоже нравится этот вариант. 

Пушнул последние изменения, просьба проверить

2021-05-14 05:32 UTC, arikai commented on proto/domain.thrift
> +struct TradeBloc {
> Правда эпик не рассчитывает на то, что у одной страны может быть скажем 7 экономических зон
С учётом того, что пока Блок будет только один – не станет проблемой. 
Даже сейчас при выгрузке отчётов имена блоков можно, например, разделять через запятую. (если я правильно представляю их формат).

Больший вопрос: версионность Блоков. Для выгрузки *текущих* отчётов проблем нет – данные будут браться актуальные. При обращении же к историческим данным нужно иметь возможность понять, в каких блоках состояла страна на тот или иной момент.

Имеет смысл? 🤔

2021-05-14 06:41 UTC, kpy3 commented on proto/domain.thrift
> +struct TradeBloc {
Оно же выгружается из лога (кафки) там оно уже "правильно" записано. А при переналивке топика значение будет браться из событий, которые записаны в риаке, то есть, такой проблемы не должно возникать. 🤔

2021-05-14 07:28 UTC, kpy3 approved these changes

2021-05-14 07:28 UTC, kpy3 commented
LGTM

2021-05-14 07:52 UTC, arikai commented on proto/domain.thrift
> +struct TradeBloc {
Вероятно, уже более общую картину представляю (где ещё данная модель данных может использоваться).

Не полностью разбираюсь в системе, поэтому и возникает вопрос (возможно, повторюсь): нет/не будет ли сценариев (не только по отношению к отчётам), где для работы с историческими данными нужно будет получить состояние Блока (его состав) на тот момент? 

>А при переналивке топика значение будет браться из событий, которые записаны в риаке, то есть, такой проблемы не должно возникать. 🤔

Правильно ли я понимаю твоё объяснение, что в таких сценариях вся информация закодирована в соотв. событиях? 🤔

2021-05-14 07:53 UTC, arikai commented on proto/domain.thrift
> +struct TradeBloc {
@tolkonepiu текущая схема подходит?

2021-05-14 07:53 UTC, kpy3 commented on proto/domain.thrift
> +struct TradeBloc {
Да, по-идее она должна быть в соотв. событиях

2021-05-14 07:54 UTC, arikai commented on proto/domain.thrift
> +struct TradeBloc {
> Да, по-идее она должна быть в соотв. событиях

Для проверки: @keynslug, нет ошибки в рассуждениях?

2021-05-14 09:37 UTC, keynslug commented on proto/domain.thrift
> +struct TradeBloc {
> ...для работы с историческими данными нужно будет получить состояние Блока (его состав) на тот момент?
> Правильно ли я понимаю твоё объяснение, что в таких сценариях вся информация закодирована в соотв. событиях? 🤔 

Вообще в подавляющем большинстве случаев это решается version lock'ом данных domain config, который достигается тем, что в большинстве сущностей, данные которых попадают в ивенты, мы сохраняем [`DomainRevision`](https://github.com/rbkmoney/damsel/blob/79e933e3518ad23eb39864a744e4851961370f23/proto/domain.thrift#L193). На первый взгляд этого механизма должно быть достаточно.

2021-05-14 11:36 UTC, arikai commented on proto/domain.thrift
> +struct TradeBloc {
> На первый взгляд этого механизма должно быть достаточно.

Да, звучит как то, что нужно.

2021-05-14 11:39 UTC, tolkonepiu approved these changes

2021-05-14 12:12 UTC, merged