JD-540: add INN to RussianPrivateEntity
rbkmoney/damsel pull request #712
Opened 2021-09-03 14:08 UTC by mr-impossibru

Для обеспечения уникальности клиентов нам необходимо ИНН в RussianPrivateEntity.
Субъективно, выглядит так будто его забыли включить в модель, в остальных, специфических для России, сущностях он есть.

2021-09-03 14:09 UTC, tolkonepiu requested changes

2021-09-03 14:09 UTC, tolkonepiu commented on proto/domain.thrift
> +    5: required string inn;
```suggestion
    5: required string inn
```

2021-09-03 14:11 UTC, mr-impossibru commented on proto/domain.thrift
> +    5: required string inn;
поправил

2021-09-06 08:43 UTC, keynslug reviewed
Вообще private entity вводился _исключительно_ для нужд b2c-кошельков (на базе fistful), и там на этапе регистрации _нового_ клиента мы не то чтобы имели возможность спрашивать у клиента ИНН. Поэтому и тут его нет.

Если его добавить в виде required поля, то:
* сломается party-management (потому что в текущих данных нет ИНН, и взять его неоткуда),
* сломается интеграция fistful (потому что ему тоже неоткуда его взять).

Как вариант можно конечно возложить через изменение swag-wallets обязательство за его передачу на клиентов, то тут я не готов оценить насколько это оправдано. @tolkonepiu?

2021-09-06 11:50 UTC, tolkonepiu commented
@keynslug не оправданно, думали, что это просто ИПшники

2021-09-06 11:58 UTC, mr-impossibru commented
Понял свою ошибку

![](https://i.imgflip.com/5m1g7p.jpg)

2021-09-06 11:58 UTC, closed without merging